name: Create Release Tag

on:
  push:
    tags:
      - 'icon*' # Push events to matching icon*, i.e. icon-vue@1.0, icon-vue@20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release for Tag
        id: release_tag
        uses: yyx990803/release-tag@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body: |
            更新内容参见 packages 中 changelog.md.
